# Generated by Django 2.0.7 on 2018-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
