# Generated by Django 2.0.7 on 2018-07-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_repost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='content',
        ),
    ]
