# Generated by Django 2.0.7 on 2018-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0011_remove_repost_content")]

    operations = [
        migrations.AddField(
            model_name="repost", name="content", field=models.TextField(blank=True)
        )
    ]
